INSERT INTO email (
  send_email, name, account_id, user_id, subject, text, content, 
  to_email, to_name, type, status, create_time, is_del, is_read
) VALUES 
(
  'auggie@augmentcode.com', 
  'Augment Code', 
  3, 
  3, 
  'Welcome to Augment Code', 
  'Your verification code is: 123456', 
  '<html><body><h2>Welcome to Augment Code</h2><p>Your verification code is: <strong>123456</strong></p></body></html>', 
  'admin@example.com', 
  'Admin', 
  0, 
  1, 
  datetime('now'), 
  0, 
  0
),
(
  'auggie@augmentcode.com', 
  'Augment Code', 
  3, 
  3, 
  'Welcome to Augment Code', 
  'Your verification code is: 789012', 
  '<html><body><h2>Welcome to Augment Code</h2><p>Your verification code is: <strong>789012</strong></p></body></html>', 
  'admin@example.com', 
  'Admin', 
  0, 
  1, 
  datetime('now', '-1 hour'), 
  0, 
  0
),
(
  'auggie@augmentcode.com', 
  'Augment Code', 
  3, 
  3, 
  'Welcome to Augment Code', 
  'Your verification code is: 345678', 
  '<html><body><h2>Welcome to Augment Code</h2><p>Your verification code is: <strong>345678</strong></p></body></html>', 
  'admin@example.com', 
  'Admin', 
  0, 
  1, 
  datetime('now', '-2 hours'), 
  0, 
  0
),
(
  'auggie@augmentcode.com', 
  'Augment Code', 
  3, 
  3, 
  'Welcome to Augment Code', 
  'Your verification code is: 456789', 
  '<html><body><h2>Welcome to Augment Code</h2><p>Your verification code is: <strong>456789</strong></p></body></html>', 
  'admin@example.com', 
  'Admin', 
  0, 
  1, 
  datetime('now', '-3 hours'), 
  0, 
  0
),
(
  'auggie@augmentcode.com', 
  'Augment Code', 
  3, 
  3, 
  'Welcome to Augment Code', 
  'Your verification code is: 901234', 
  '<html><body><h2>Welcome to Augment Code</h2><p>Your verification code is: <strong>901234</strong></p></body></html>', 
  'admin@example.com', 
  'Admin', 
  0, 
  1, 
  datetime('now', '-4 hours'), 
  0, 
  0
);
